### ISSUE TITLE
It doesn't work to save last build SHA in CircleCI cache

### ISSUE THREAD

**Issue by oscar60310** [nrwl/nx-examples#225]
We saved the last build SHA in CircleCI cache as the reference for next build
https://github.com/nrwl/nx-examples/blob/master/.circleci/config.yml#L139-L142
```yaml
- save_cache:
    key: last-deploy-sha
    paths:
      - dist/last-deploy.txt
```
But CircleCI cache is [immutable](https://circleci.com/docs/caching-strategy), so saving an existing cache doesn't take any effect.
```
Skipping cache generation, cache already exists for key: last-deploy-sha
Found one created at 2022-08-29 17:03:12 +0000 UTC
```
We should find other solutions to save the SHA.
